name: Docker Image CI develop

on:
  push:
    branches:    
    - develop

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ampache:develop
